
#
#config file for sun50iw9
#
ARCH = arm
PLATFORM = sun50iw9p1

CFG_BOOT0_RUN_ADDR=0x20000
CFG_SYS_INIT_RAM_SIZE=0x10000
CFG_FES1_RUN_ADDR=0x28000
CFG_SBOOT_RUN_ADDR=0x20480

#power
CFG_SUNXI_POWER=y
CFG_SUNXI_TWI=y
CFG_SUNXI_PMIC=y
CFG_AXP1530_POWER=y
CFG_AXP858_POWER=y
CFG_AXP806_POWER=y
CFG_SUNXI_STANDBY=y

#chipid
CFG_SUNXI_CHIPID=y

#key
CFG_SUNXI_PHY_KEY=y
CFG_GPADC_KEY=y

#sunxi selet dram para
CFG_SUNXI_SELECT_DRAM_PARA=y
DRAM_TYPE_NAME=
