#
# Makefile for the SPINAND MTD
#

obj-$(CONFIG_AW_MTD_SPINAND) += aw-spinand.o

aw-spinand-objs += sunxi-core.o sunxi-driver.o sunxi-ubi.o secure-storage.o

obj-$(CONFIG_AW_SPINAND_PHYSICAL_LAYER) += physic/
