#
# (C) Copyright 2008-2015
#
# SPDX-License-Identifier:	GPL-2.0+
#


obj-y +=  CRYPTO_malloc.o

obj-y +=  err/err.o

obj-y +=  objects/obj_dat.o

obj-y +=  asn1/a_int.o asn1/asn1_get_field_ptr.o asn1/ASN1_INTEGER_get.o asn1/asn1_item_ex_new.o  \
            asn1/asn1_lock_free.o asn1/asn1_new_free.o asn1/asn1_put_object.o asn1/asn1_string.o    \
            asn1/ASN1_STRING_print.o asn1/d2i_pu.o asn1/d2i_rsapublikey.o asn1/EVP_pkey.o           \
            asn1/i2a_ASN1_INTEGER.o asn1/i2d_pu.o asn1/X509_PUBKEY_it.o asn1/x_bignum.o             \
            asn1/x_x509.o asn1/RSAPublicKey_it.o  asn1/tasn_enc.o asn1/stk.o asn1/x509_extension_it.o

obj-y +=  x509/x509_v3.o x509/x509_ext.o x509/extension.o

obj-y +=  bn/bn_lib.o bn/bn_word.o bn/bn_bn2dec.o bn/bn_print.o bn/bn_asm.o bn/bn_shift.o

obj-y +=  bio/bio.o bio/b_print.o bio/bio_free.o bio/bio_s_mem.o bio/bio_read.o

obj-y +=  lhash/lh_retrieve.o

obj-y +=  rsa/rsa.o

obj-y +=  external/openssl_ext.o

