#
# Makefile for rawnand
#
#
#

obj-$(CONFIG_SUNXI_NAND) += rawnand_ids.o
obj-$(CONFIG_SUNXI_NAND) += rawnand_base.o
obj-$(CONFIG_SUNXI_NAND) += rawnand_boot0.o
obj-$(CONFIG_SUNXI_NAND) += rawnand_ops.o
obj-$(CONFIG_SUNXI_NAND) += rawnand_readretry.o
obj-$(CONFIG_SUNXI_NAND) += rawnand_boot1.o
#obj-$(CONFIG_SUNXI_NAND) += version.o
obj-$(CONFIG_SUNXI_NAND) += rawnand_cfg.o
obj-$(CONFIG_SUNXI_NAND) += rawnand_cfg.o
obj-$(CONFIG_SUNXI_NAND) += rawnand_debug.o
obj-$(CONFIG_SUNXI_NAND) += rawnand_chip.o
obj-$(CONFIG_SUNXI_NAND) += rawnand_timings.o
#obj-y += chip/
obj-y += controller/
#obj-$(CONFIG_SUNXI_NAND) += nand_id2.o
#obj-$(CONFIG_SUNXI_NAND) += nand_phy_init.o
#obj-$(CONFIG_SUNXI_NAND) += nand_physic_interface_rawnand.o
#obj-$(CONFIG_SUNXI_NAND) += nand_platform_data.o
#obj-y += adapter/
#obj-y += hynix/
#obj-y += universal/
