#
# Makefile for phy-nand
#


obj-$(CONFIG_SUNXI_NAND) += version.o
obj-$(CONFIG_SUNXI_NAND) += nand_physic_interface.o
obj-$(CONFIG_SUNXI_NAND) += nand_secure_storage.o
obj-$(CONFIG_SUNXI_NAND) += nand_boot.o
obj-$(CONFIG_SUNXI_NAND) += nand_weak.o

obj-$(CONFIG_SUNXI_NAND) += nand-partition/
obj-$(CONFIG_SUNXI_NAND) += nand-partition2/
obj-$(CONFIG_SUNXI_NAND) += rawnand/
obj-$(CONFIG_SUNXI_NAND) += spinand/
