obj-$(CONFIG_HDMI_DISP2_SUNXI) += hdmi.o

hdmi-y := drv_hdmi.o hdmi_core.o hdmi_edid.o
hdmi-$(CONFIG_MACH_SUN50IW1) += libhdmi_sun50iw1
hdmi-$(CONFIG_MACH_SUN50IW2) += libhdmi_sun50iw1
hdmi-$(CONFIG_MACH_SUN8IW11) += hdmi_bsp_sun8iw11.o
hdmi-$(CONFIG_MACH_SUN8IW12) += hdmi_bsp_sun8iw12.o
hdmi-$(CONFIG_MACH_SUN8IW15) += hdmi_bsp_sun8iw12.o
hdmi-$(CONFIG_MACH_SUN8IW7) += hdmi_bsp_sun8iw7.o
hdmi-$(CONFIG_MACH_SUN8IW6) += hdmi_bsp_sun8iw6.o
