#
# Copyright (c) 2015 Allwinnertech, Inc.
# Tyle <tyle at allwinnertech.com>
#
#

obj-$(CONFIG_DISP2_SUNXI) += disp2/

obj-$(CONFIG_BOOT_GUI) += bootGUI/

obj-y += logo_display/
obj-$(CONFIG_EINK200_SUNXI) += disp2/eink200/
obj-$(CONFIG_EINK200_SUNXI) += common/eink_v2.o
