/*
 * u-boot-2014.07/include/sunxi_advert/sunxi_advert.h
 *
 * Copyright (c) 2007-2018 Allwinnertech Co., Ltd.
 * Author: zhengxiaobin <zhengxiaobin@allwinnertech.com>
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
#ifndef _SUNXI_ADVERT_H_
#define _SUNXI_ADVERT_H_

#define ADVERT_MAGIC "advert-group"
#define ADVERT_VERSION "0100"

struct __advert_head {
	u8 magic[16];    /*"advert-group" */
	u8 version[4];   /*"0100" */
	u8 partname[16]; /* partition name */
	u32 check_sum;   /* generated by android */
	u32 length;      /* logo file length */
	u8 filename[16]; /*picture name:advert.bmp */
	u8 reserve[452]; /* 512-16-4-16-4-4-16 = 452 */
};

#endif
