#
# Copyright (c) 2015 Allwinnertech, Inc.
# Tyle <tyle at allwinnertech.com>
#
#

obj-y += disp/
obj-$(CONFIG_HDMI_DISP2_SUNXI) += hdmi/
obj-$(CONFIG_HDMI2_DISP2_SUNXI) += hdmi2/
obj-$(CONFIG_TV_DISP2_SUNXI) += tv/
obj-$(CONFIG_EDP_DISP2_SUNXI) += edp/
