

obj-$(CONFIG_SUNXI_COMM_NAND_V1) += nand_osal_uboot.o
obj-$(CONFIG_SUNXI_COMM_NAND_V1) += nand_uboot_fun.o
obj-$(CONFIG_SUNXI_COMM_NAND_V1) += nand_for_clock_v0.o
obj-$(CONFIG_SUNXI_COMM_NAND_V1) += nand_for_clock_v1.o
obj-$(CONFIG_SUNXI_COMM_NAND_V1) += phy2nftl.o
obj-$(CONFIG_SUNXI_COMM_NAND_V1) += phy-nand/


obj-$(CONFIG_SUNXI_COMM_NAND_V1) += nftl.o
