# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2018www.allwinner.tech
#
# Based on some other board Makefile
#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_SUNXI_USB)	+= usbc.o usbc_dev.o usbc_dma.o usbc_host.o usbc_phy.o
obj-$(CONFIG_SUNXI_USB)	+= usb_base_common.o usb_base_platform.o usb_dma_control.o
obj-$(CONFIG_SUNXI_EFEX) += usb_efex.o efex_queue.o buf_queue.o
obj-$(CONFIG_SUNXI_BURN) += usb_burn.o
obj-$(CONFIG_SUNXI_FASTBOOT) += usb_fastboot.o
