#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done
echo 7 4 1 7 > /proc/sys/kernel/printk
echo 5 > /proc/sys/kernel/panic

ifconfig eth0 up

#insmod /lib/modules/8189fs.ko
#insmod /lib/modules/ns2009.ko
#sleep 1
#wpa_supplicant -D wext -i wlan0 -c /etc/wpa_supplicant.conf &
#sleep 2
#udhcpc -i wlan0 &
