
# define sources root directory before everything
SRC_ROOT := ../

# include rule.mk
include ../rule.mk

# add you test case here
.PHONY: all
all:
	#make -C stp_uart_launcher
	#make -C write_devnode
	cp -rf hawkview $(BINDIR)/
