# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2018 Allwinner Technology.
# wangwei <wangwei@allwinnertech.com>
obj-$(CONFIG_SUNXI_BOX_STANDBY) += box_standby.o
obj-$(CONFIG_ATF_BOX_STANDBY) += atf_box_standby.o
obj-$(CONFIG_IR_BOOT_RECOVERY) += ir-recovery.o
obj-$(CONFIG_SUNXI_HDCP_IN_SECURESTORAGE) += sunxi_hdcp_key.o
obj-$(CONFIG_SUNXI_CHECK_CUSTOMER_RESERVED_ID) += sunxi_check_necessary_verify.o
