obj-$(CONFIG_TV_DISP2_SUNXI) += tv.o

tv-$(CONFIG_MACH_SUN50IW1) := tv_ac200.o tv_ac200_lowlevel.o
tv-$(CONFIG_MACH_SUN8IW11) := drv_tv.o de_tve_sun8iw11.o
tv-$(CONFIG_MACH_SUN50IW2) := drv_tv.o de_tve_v1.o
tv-$(CONFIG_MACH_SUN50IW6) := tv_ac200.o tv_ac200_lowlevel.o
tv-$(CONFIG_MACH_SUN8IW12) := drv_tv.o de_tve_sun8iw11.o
tv-$(CONFIG_MACH_SUN8IW16) := drv_tv.o de_tve_sun8iw11.o
tv-$(CONFIG_MACH_SUN8IW7) := drv_tv.o de_tve_sun8iw7.o
tv-$(CONFIG_MACH_SUN8IW17) := drv_tv.o de_tve_sun8iw11.o
tv-$(CONFIG_MACH_SUN50IW9) := drv_tv.o de_tve_sun8iw11.o
