# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2018 Allwinner Technology.
# wangwei <wangwei@allwinnertech.com>
obj-$(CONFIG_SUNXI_AVB) += sunxi_avb.o
obj-$(CONFIG_SUNXI_ANDROID_BOOT) += sunxi_android_boot.o
