# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2018 Allwinner Technology.
# wangwei <wangwei@allwinnertech.com>
obj-$(CONFIG_SUNXI_IR) += bitrev.o
obj-$(CONFIG_SUNXI_IR) += sunxi-ir.o
obj-$(CONFIG_SUNXI_IR_NEC_DECODE) += ir-nec-decode.o
